// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6SI1pDm98F0QJgmLDuSbtql1CeXhC1cw',
    appId: '1:93310472122:web:3338814d924deea4679783',
    messagingSenderId: '93310472122',
    projectId: 'test-project-60ac9',
    authDomain: 'test-project-60ac9.firebaseapp.com',
    storageBucket: 'test-project-60ac9.firebasestorage.app',
    measurementId: 'G-8574F38RR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtyNFajYkM11O9aiGQFfEICCAiMaqoHLE',
    appId: '1:93310472122:android:0d0a77594d9d85e7679783',
    messagingSenderId: '93310472122',
    projectId: 'test-project-60ac9',
    storageBucket: 'test-project-60ac9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlYQ49qTtWtWj16osoIpCMs2KMj5AOW_k',
    appId: '1:93310472122:ios:20fedbcc6a194ec4679783',
    messagingSenderId: '93310472122',
    projectId: 'test-project-60ac9',
    storageBucket: 'test-project-60ac9.firebasestorage.app',
    iosBundleId: 'com.example.thuchanhFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlYQ49qTtWtWj16osoIpCMs2KMj5AOW_k',
    appId: '1:93310472122:ios:20fedbcc6a194ec4679783',
    messagingSenderId: '93310472122',
    projectId: 'test-project-60ac9',
    storageBucket: 'test-project-60ac9.firebasestorage.app',
    iosBundleId: 'com.example.thuchanhFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6SI1pDm98F0QJgmLDuSbtql1CeXhC1cw',
    appId: '1:93310472122:web:5db756d6a01a3c76679783',
    messagingSenderId: '93310472122',
    projectId: 'test-project-60ac9',
    authDomain: 'test-project-60ac9.firebaseapp.com',
    storageBucket: 'test-project-60ac9.firebasestorage.app',
    measurementId: 'G-YJTSEE7RJY',
  );
}
